import type { Metadata } from "next";
import "./globals.css";
import 'leaflet/dist/leaflet.css';
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";


const outfit = localFont({
  src: [
    { path: "/fonts/Outfit-Bold.ttf", weight: "700", style: "normal" },
    { path: "/fonts/Outfit-Regular.ttf", weight: "400", style: "normal" },
    { path: "/fonts/Outfit-Medium.ttf", weight: "500", style: "normal" },
    { path: "/fonts/Outfit-SemiBold.ttf", weight: "600", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ClerkProvider
      appearance={{
        layout: {
          socialButtonsVariant: "iconButton",
          logoImageUrl: "/icons/scango.svg",
        },
        variables: {
          colorText: "#252525",
          colorPrimary: "#0E78F9",
          colorBackground: "#fff",
          colorInputBackground: "#F8F8FF",
          colorInputText: "#252525",
        },
      }}
      >
        <body className={`${outfit.className} antialiased`}>{children}
        <Toaster />
        </body>
      </ClerkProvider>
    </html>
  );
}
