import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import localFont from "next/font/local";


const outfit = localFont({
  src: [
    { path: "/fonts/Outfit-Bold.ttf", weight: "700", style: "normal" },
    { path: "/fonts/Outfit-Regular.ttf", weight: "400", style: "normal" },
    { path: "/fonts/Outfit-Medium.ttf", weight: "500", style: "normal" },
    { path: "/fonts/Outfit-SemiBold.ttf", weight: "600", style: "normal" },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body className={`${outfit.className} antialiased`}>{children}</body>
      </ClerkProvider>
    </html>
  );
}
